### ISSUE TITLE
Model should accept more than two players.

### ISSUE THREAD

**Issue by aannenko** [aannenko/noughts-and-crosses#4]
Let's make a model which works with indefinite number of players using the following new objects:
1. An Iterator object should receive an array of players and allow to iterate over them using a GetNext() function.
2. A PlayerFactory object should resolve a configured player (human or computer, see factory pattern).
3. The Game object in its constructor should receive an array of players created by ViewModel using the PlayerFactory object.

**Comment by KassandraA** [comment]
1. Done (Iterator has moveNext and getCurrent methods)
2. Done
3. Done
