### ISSUE TITLE
The ViewModel part should provide an API that will allow to get and set game data before game starts.

### ISSUE THREAD

**Issue by aannenko** [aannenko/noughts-and-crosses#5]
The ViewModel part should have an _API that will provide default data_, that the game uses during initialization, and will _allow the View part to change this data_ at its discretion.
Because the ViewModel part will use this data to initialize a new game, this _API should be accessible and functional before the game starts_.

**The following section of this issue does not describe the actual task. It only provides information on how the resulting code will be used:**

The overall flow of this data is the following:
1. Page loads, the View part reads the data from the ViewModel part using the aforementioned API and shows this data to a user.
2. User changes the data on the page and the View part uses the API in the ViewModel part to change this data accordingly.
3. User starts the game, the ViewModel part reads the data and initializes the game accordingly.

**Comment by KassandraA** [comment]
I'he added methods [getPlayer], [setPlayer], [addPlayer], [deletePlayer] to [gamePreset] object.
I have several questios.
1) Is it ok adding players to the end of the players array and delete it from any part of the array without rebiulding [playersId]? After such deleting, for example elenemt with id='03', we may get an array such as [01, 02, 04, 05].
2) We need to add playerId parameter to the [Factory].
3) Do we need to limit the number of players (untill we increase game field)?
4) I think we need to change [type] property of a player to boolean, like [isHuman: true/false].

**Comment by aannenko** [comment]
Cool! Nice to see these questions here before the task is implemented! :)

> Is it ok adding players to the end of the players array and delete it from any part of the array without rebiulding [playersId]? After such deleting, for example elenemt with id='03', we may get an array such as [01, 02, 04, 05].

I think, implementing IDs for players should not be done during this task, though you will encounter a task with this matter pretty soon. :) If you want to know more about IDs and how to make them really independent, I suggest googling the "GUID" word and reading through first several search results. After that you also can search for info on how to generate and use GUIDs in JS.

> We need to add playerId parameter to the [Factory].

As I've already mentioned, there's no need to implement IDs in this task. During this task the model part and the view part should remain untouched.

> Do we need to limit the number of players (untill we increase game field)?

We don't have to limit a number of players anywhere at the moment because there are just no controls in the view part that can manipulate the amount of players and their qualities. For now the viewmodel part will just have a kind of base set of players with default qualities (name, sign, type) which will be used always (until this is changed in the future tasks).

> I think we need to change [type] property of a player to boolean, like [isHuman: true/false].

The [type] property is not limited to `human` and `computer` options. Imagine a case where two players play this game on the internet (they are not sitting in front of the same physical machine). In this case we will need another type of player - a `remoteHuman`, that will inherit its functionality from the base player but will also have some additional functionality related to the network play.

I suppose, the only thing you have to do during this task is to create an array of players (an object literal) with some default players inside (AFAIK, you already have one), and a set of methods to get, set, add and remove players from this array. Don't bother yourself making the players array encapsulated, this array will be removed pretty soon and then will be recreated in the model. After you remove this array from the viewmodel, you will still have these `get()`, `set()` (I believe that there is a better name for this method), `add()` and `delete()` methods there, which will be modified a bit to use model's functionality to set up the game.
